/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogoVelha;

import javax.swing.JOptionPane;

/**
 *
 * @author a120121
 */
public class TelaVelha extends javax.swing.JFrame {

    private Velha velha;
    private Jogador j1, j2; //usar diretamente o da classe Velha (arrumar)
    private Jogador jogadorAtual;

    public TelaVelha() {
        j1 = new Jogador();
        j2 = new Jogador();
        jogadorAtual = j1;
        velha = new Velha(j1, j2);
        initComponents();
    }

    public void atualizarPlacar() {
        if (velha.getFim()) {
            if (velha.getVencedor() == null) {
                campoPlacarVelha.setText(Integer.toString(Integer.parseInt(campoPlacarVelha.getText()) + 1));
                JOptionPane.showMessageDialog(null, "Deu Velha!", "FIM DE JOGO", 1);
            } else if (velha.getVencedor() == j1) {
                campoPlacarJ1.setText(Integer.toString(Integer.parseInt(campoPlacarJ1.getText()) + 1));
                JOptionPane.showMessageDialog(null, "O Jogador 1 ganhou!", "FIM DE JOGO", 1);
            } else {
                campoPlacarJ2.setText(Integer.toString(Integer.parseInt(campoPlacarJ2.getText()) + 1));
                JOptionPane.showMessageDialog(null, "O Jogador 2 ganhou!", "FIM DE JOGO", 1);
            }
            velha.setFim(false);
            velha.setVencedor(null);
            botaoPos1.setEnabled(false);
            botaoPos2.setEnabled(false);
            botaoPos3.setEnabled(false);
            botaoPos4.setEnabled(false);
            botaoPos5.setEnabled(false);
            botaoPos6.setEnabled(false);
            botaoPos7.setEnabled(false);
            botaoPos8.setEnabled(false);
            botaoPos9.setEnabled(false);
            for (int c = 0; c < 9; c++) {
                velha.getJogadas()[c] = null;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CampoNomeJ1 = new javax.swing.JTextField();
        CampoNomeJ2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CampoSimboloJ1 = new javax.swing.JTextField();
        CampoSimboloJ2 = new javax.swing.JTextField();
        botaoReiniciar = new javax.swing.JButton();
        botaoIniciar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        botaoPos1 = new javax.swing.JButton();
        botaoPos2 = new javax.swing.JButton();
        botaoPos3 = new javax.swing.JButton();
        botaoPos4 = new javax.swing.JButton();
        botaoPos5 = new javax.swing.JButton();
        botaoPos6 = new javax.swing.JButton();
        botaoPos7 = new javax.swing.JButton();
        botaoPos8 = new javax.swing.JButton();
        botaoPos9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoPlacarJ1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoPlacarJ2 = new javax.swing.JTextField();
        campoPlacarVelha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JOGO DA VELHA");

        jPanel1.setBackground(new java.awt.Color(205, 239, 252));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informaões e Opções:"));

        jLabel1.setText("Jogador 1:");

        jLabel2.setText("Jogador 2:");

        jLabel3.setText("Símbolo 1:");

        jLabel4.setText("Símbolo 2:");

        botaoReiniciar.setText("REINICIAR");
        botaoReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoReiniciarActionPerformed(evt);
            }
        });

        botaoIniciar.setText("INICIAR");
        botaoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoNomeJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoSimboloJ1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(CampoNomeJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoSimboloJ2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botaoReiniciar)
                                .addGap(18, 18, 18)
                                .addComponent(botaoIniciar)
                                .addGap(112, 112, 112)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CampoNomeJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(CampoSimboloJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CampoNomeJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(CampoSimboloJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoReiniciar)
                    .addComponent(botaoIniciar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo:"));

        botaoPos1.setText(" ");
        botaoPos1.setEnabled(false);
        botaoPos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPos1ActionPerformed(evt);
            }
        });

        botaoPos2.setText(" ");
        botaoPos2.setEnabled(false);
        botaoPos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPos2ActionPerformed(evt);
            }
        });

        botaoPos3.setText(" ");
        botaoPos3.setEnabled(false);
        botaoPos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPos3ActionPerformed(evt);
            }
        });

        botaoPos4.setText(" ");
        botaoPos4.setEnabled(false);
        botaoPos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPos4ActionPerformed(evt);
            }
        });

        botaoPos5.setText(" ");
        botaoPos5.setEnabled(false);
        botaoPos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPos5ActionPerformed(evt);
            }
        });

        botaoPos6.setText(" ");
        botaoPos6.setEnabled(false);
        botaoPos6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPos6ActionPerformed(evt);
            }
        });

        botaoPos7.setText(" ");
        botaoPos7.setEnabled(false);
        botaoPos7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPos7ActionPerformed(evt);
            }
        });

        botaoPos8.setText(" ");
        botaoPos8.setEnabled(false);
        botaoPos8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPos8ActionPerformed(evt);
            }
        });

        botaoPos9.setText(" ");
        botaoPos9.setEnabled(false);
        botaoPos9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPos9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(botaoPos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPos2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPos3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(botaoPos4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPos5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPos6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(botaoPos7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPos8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPos9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPos1)
                    .addComponent(botaoPos2)
                    .addComponent(botaoPos3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPos4)
                    .addComponent(botaoPos5)
                    .addComponent(botaoPos6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPos7)
                    .addComponent(botaoPos8)
                    .addComponent(botaoPos9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Placar"));

        jLabel5.setText("Jogador 1:");

        jLabel6.setText("Jogador 2:");

        campoPlacarJ1.setEditable(false);
        campoPlacarJ1.setText("0");

        jLabel7.setText("Velha:");

        campoPlacarJ2.setEditable(false);
        campoPlacarJ2.setText("0");

        campoPlacarVelha.setEditable(false);
        campoPlacarVelha.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPlacarJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPlacarJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoPlacarVelha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoPlacarJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoPlacarJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoPlacarVelha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPos1ActionPerformed
        velha.inserirJogada(jogadorAtual, 1);
        if (jogadorAtual == j1) {
            botaoPos1.setText(CampoSimboloJ1.getText());
            jogadorAtual = j2;
        } else {
            botaoPos1.setText(CampoSimboloJ2.getText());
            jogadorAtual = j1;
        }
        botaoPos1.setEnabled(false);
        atualizarPlacar();
    }//GEN-LAST:event_botaoPos1ActionPerformed

    private void botaoPos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPos2ActionPerformed
        velha.inserirJogada(jogadorAtual, 2);
        if (jogadorAtual == j1) {
            botaoPos2.setText(CampoSimboloJ1.getText());
            jogadorAtual = j2;
        } else {
            botaoPos2.setText(CampoSimboloJ2.getText());
            jogadorAtual = j1;
        }
        botaoPos2.setEnabled(false);
        atualizarPlacar();
    }//GEN-LAST:event_botaoPos2ActionPerformed

    private void botaoPos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPos3ActionPerformed
        velha.inserirJogada(jogadorAtual, 3);
        if (jogadorAtual == j1) {
            botaoPos3.setText(CampoSimboloJ1.getText());
            jogadorAtual = j2;
        } else {
            botaoPos3.setText(CampoSimboloJ2.getText());
            jogadorAtual = j1;
        }
        botaoPos3.setEnabled(false);
        atualizarPlacar();
    }//GEN-LAST:event_botaoPos3ActionPerformed

    private void botaoPos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPos4ActionPerformed
        velha.inserirJogada(jogadorAtual, 4);
        if (jogadorAtual == j1) {
            botaoPos4.setText(CampoSimboloJ1.getText());
            jogadorAtual = j2;
        } else {
            botaoPos4.setText(CampoSimboloJ2.getText());
            jogadorAtual = j1;
        }
        botaoPos4.setEnabled(false);
        atualizarPlacar();
    }//GEN-LAST:event_botaoPos4ActionPerformed

    private void botaoPos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPos5ActionPerformed
        velha.inserirJogada(jogadorAtual, 5);
        if (jogadorAtual == j1) {
            botaoPos5.setText(CampoSimboloJ1.getText());
            jogadorAtual = j2;
        } else {
            botaoPos5.setText(CampoSimboloJ2.getText());
            jogadorAtual = j1;
        }
        botaoPos5.setEnabled(false);
        atualizarPlacar();
    }//GEN-LAST:event_botaoPos5ActionPerformed

    private void botaoPos6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPos6ActionPerformed
        velha.inserirJogada(jogadorAtual, 6);
        if (jogadorAtual == j1) {
            botaoPos6.setText(CampoSimboloJ1.getText());
            jogadorAtual = j2;
        } else {
            botaoPos6.setText(CampoSimboloJ2.getText());
            jogadorAtual = j1;
        }
        botaoPos6.setEnabled(false);
        atualizarPlacar();
    }//GEN-LAST:event_botaoPos6ActionPerformed

    private void botaoPos7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPos7ActionPerformed
        velha.inserirJogada(jogadorAtual, 7);
        if (jogadorAtual == j1) {
            botaoPos7.setText(CampoSimboloJ1.getText());
            jogadorAtual = j2;
        } else {
            botaoPos7.setText(CampoSimboloJ2.getText());
            jogadorAtual = j1;
        }
        botaoPos7.setEnabled(false);
        atualizarPlacar();
    }//GEN-LAST:event_botaoPos7ActionPerformed

    private void botaoPos8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPos8ActionPerformed
        velha.inserirJogada(jogadorAtual, 8);
        if (jogadorAtual == j1) {
            botaoPos8.setText(CampoSimboloJ1.getText());
            jogadorAtual = j2;
        } else {
            botaoPos8.setText(CampoSimboloJ2.getText());
            jogadorAtual = j1;
        }
        botaoPos8.setEnabled(false);
        atualizarPlacar();
    }//GEN-LAST:event_botaoPos8ActionPerformed

    private void botaoPos9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPos9ActionPerformed
        velha.inserirJogada(jogadorAtual, 9);
        if (jogadorAtual == j1) {
            botaoPos9.setText(CampoSimboloJ1.getText());
            jogadorAtual = j2;
        } else {
            botaoPos9.setText(CampoSimboloJ2.getText());
            jogadorAtual = j1;
        }
        botaoPos9.setEnabled(false);
        atualizarPlacar();
    }//GEN-LAST:event_botaoPos9ActionPerformed

    private void botaoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarActionPerformed
        if (CampoNomeJ1.getText().equals("") == false && CampoNomeJ2.getText().equals("") == false && CampoSimboloJ1.getText().equals("") == false && CampoSimboloJ2.getText().equals("") == false) {
            if (CampoSimboloJ1.getText().equals(CampoSimboloJ2.getText()) == false) {
                CampoNomeJ1.setEditable(false);
                CampoNomeJ2.setEditable(false);
                CampoSimboloJ1.setEditable(false);
                CampoSimboloJ2.setEditable(false);
                botaoIniciar.setEnabled(false);
                botaoPos1.setEnabled(true);
                botaoPos2.setEnabled(true);
                botaoPos3.setEnabled(true);
                botaoPos4.setEnabled(true);
                botaoPos5.setEnabled(true);
                botaoPos6.setEnabled(true);
                botaoPos7.setEnabled(true);
                botaoPos8.setEnabled(true);
                botaoPos9.setEnabled(true);
                j1.setNome(CampoNomeJ1.getText());
                j2.setNome(CampoNomeJ2.getText());
                j1.setSimbolo(CampoSimboloJ1.getText());
                j2.setSimbolo(CampoSimboloJ2.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Símbolos não podem ser idênticos!", "MENSAGEM", 0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum campo pode ser nulo!", "MENSAGEM", 0);
        }
    }//GEN-LAST:event_botaoIniciarActionPerformed

    private void botaoReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoReiniciarActionPerformed
        CampoNomeJ1.setEditable(true);
        CampoNomeJ2.setEditable(true);
        CampoSimboloJ1.setEditable(true);
        CampoSimboloJ2.setEditable(true);
        botaoIniciar.setEnabled(true);
        botaoPos1.setText(" ");
        botaoPos2.setText(" ");
        botaoPos3.setText(" ");
        botaoPos4.setText(" ");
        botaoPos5.setText(" ");
        botaoPos6.setText(" ");
        botaoPos7.setText(" ");
        botaoPos8.setText(" ");
        botaoPos9.setText(" ");
        botaoPos1.setEnabled(false);
        botaoPos2.setEnabled(false);
        botaoPos3.setEnabled(false);
        botaoPos4.setEnabled(false);
        botaoPos5.setEnabled(false);
        botaoPos6.setEnabled(false);
        botaoPos7.setEnabled(false);
        botaoPos8.setEnabled(false);
        botaoPos9.setEnabled(false);
    }//GEN-LAST:event_botaoReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVelha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoNomeJ1;
    private javax.swing.JTextField CampoNomeJ2;
    private javax.swing.JTextField CampoSimboloJ1;
    private javax.swing.JTextField CampoSimboloJ2;
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JButton botaoPos1;
    private javax.swing.JButton botaoPos2;
    private javax.swing.JButton botaoPos3;
    private javax.swing.JButton botaoPos4;
    private javax.swing.JButton botaoPos5;
    private javax.swing.JButton botaoPos6;
    private javax.swing.JButton botaoPos7;
    private javax.swing.JButton botaoPos8;
    private javax.swing.JButton botaoPos9;
    private javax.swing.JButton botaoReiniciar;
    private javax.swing.JTextField campoPlacarJ1;
    private javax.swing.JTextField campoPlacarJ2;
    private javax.swing.JTextField campoPlacarVelha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
