/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamentoGrafico;

import javax.swing.JOptionPane;

/**
 *
 * @author rafael
 */
public class JanelaEstacionamento extends javax.swing.JFrame {

    /**
     * Creates new form JanelaEstacionamento
     */
    Estacionamento e;

    public JanelaEstacionamento() {
        e = new Estacionamento();
        initComponents();

    }

    public void atualizarLista() {
       for (int c = 0; c < e.getVAGAS().length; c++){
           if (e.getVAGAS()[c].getSituacao()){
               listaSituacao.getModel().setValueAt(e.getVAGAS()[c].getPlacaCarroAtual(), c, 1);
           } else{
               listaSituacao.getModel().setValueAt(null, c, 1);
           }
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painelOpcoes = new javax.swing.JPanel();
        botaoEstacionar = new javax.swing.JButton();
        botaoRetirar = new javax.swing.JButton();
        placaCarro = new javax.swing.JTextField();
        painelOpcoes1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaSituacao = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estacionamento");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(71, 154, 201));

        painelOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções:"));

        botaoEstacionar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botaoEstacionar.setText("Estacionar Carro");
        botaoEstacionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEstacionarMouseClicked(evt);
            }
        });
        botaoEstacionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEstacionarActionPerformed(evt);
            }
        });

        botaoRetirar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botaoRetirar.setText("Retirar Carro");
        botaoRetirar.setPreferredSize(new java.awt.Dimension(202, 32));
        botaoRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRetirarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelOpcoesLayout = new javax.swing.GroupLayout(painelOpcoes);
        painelOpcoes.setLayout(painelOpcoesLayout);
        painelOpcoesLayout.setHorizontalGroup(
            painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelOpcoesLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(botaoEstacionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(painelOpcoesLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(placaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelOpcoesLayout.setVerticalGroup(
            painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(placaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEstacionar)
                    .addComponent(botaoRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelOpcoes1.setBorder(javax.swing.BorderFactory.createTitledBorder("Situação das Vagas:"));

        listaSituacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"E1", null},
                {"E2", null},
                {"E3", null},
                {"E4", null},
                {"E5", null},
                {"E6", null},
                {"E7", null},
                {"E8", null},
                {"E9", null},
                {"E10", null},
                {"E11", null},
                {"E12", null},
                {"D1", null},
                {"D2", null},
                {"D3", null},
                {"D4", null},
                {"D5", null},
                {"D6", null},
                {"D7", null},
                {"D8", null},
                {"D9", null},
                {"D10", null},
                {"D11", null},
                {"D12", null}
            },
            new String [] {
                "Vaga", "Placa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listaSituacao);

        javax.swing.GroupLayout painelOpcoes1Layout = new javax.swing.GroupLayout(painelOpcoes1);
        painelOpcoes1.setLayout(painelOpcoes1Layout);
        painelOpcoes1Layout.setHorizontalGroup(
            painelOpcoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        painelOpcoes1Layout.setVerticalGroup(
            painelOpcoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOpcoes1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelOpcoes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelOpcoes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEstacionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEstacionarActionPerformed
        if (placaCarro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo não pode ser nulo!", "MENSAGEM", 0);
        } else {
            if (e.estacionar(placaCarro.getText())) {
                JOptionPane.showMessageDialog(null, "Vaga alugada com sucesso!", "MENSAGEM", 1);
                atualizarLista();
                placaCarro.setText(null);
            } else {
                JOptionPane.showMessageDialog(null, "Nenhuma Vaga disponível!", "MENSAGEM", 0);
            }
        }
    }//GEN-LAST:event_botaoEstacionarActionPerformed

    private void botaoRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRetirarActionPerformed
        if (placaCarro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo não pode ser nulo!", "MENSAGEM", 0);
        } else {
            long valor = e.retirar(placaCarro.getText());
            if (valor != 0) {
                JOptionPane.showMessageDialog(null, "Carro retirado com sucesso! valor total: R$" + Long.toString(valor), "MENSAGEM", 1);
                atualizarLista();
                placaCarro.setText(null);
            } else {
                JOptionPane.showMessageDialog(null, "Placa não encontrada!", "MENSAGEM", 0);
            }
        }
    }//GEN-LAST:event_botaoRetirarActionPerformed

    private void botaoEstacionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEstacionarMouseClicked
    }//GEN-LAST:event_botaoEstacionarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaEstacionamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEstacionar;
    private javax.swing.JButton botaoRetirar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaSituacao;
    private javax.swing.JPanel painelOpcoes;
    private javax.swing.JPanel painelOpcoes1;
    private javax.swing.JTextField placaCarro;
    // End of variables declaration//GEN-END:variables
}
